
"use strict";
// ======================= Trạng thái =======================
const PHASES = ["KHỞI ĐỘNG", "VẬT THẬT", "SƠ ĐỒ", "PHÉP TÍNH", "LUYỆN TẬP"];
// Bộ dữ liệu bài học — thêm 1 bài = thêm 1 dòng + chọn model đã có (không sửa code render).
// Text lấy thật từ repo ../repo (lessons.mjs: ten/khoi_dong/chot; props.mjs: ngon_tay).
const LESSONS = {
  'phan-so-dau': { model:'pie', ten:'Phân số ban đầu',
    khoi_dong:'Một cái pizza cắt cho 4 bạn, mỗi bạn một miếng. Làm sao nói gọn "một miếng trong bốn miếng bằng nhau"?',
    chot:'Mẫu số là số phần bằng nhau của cả cái, tử số là số phần được lấy; các phần phải bằng nhau tuyệt đối mới gọi là phân số.',
    obj:'miếng pizza' },
  'nhan': { model:'array', ten:'Phép nhân là cộng lặp lại', cell:'dot', rows:4, cols:6,
    khoi_dong:'Mỗi hộp có 6 cái bút và có 4 hộp. Đếm từng cái một hay có cách nào nhanh hơn?',
    chot:'a nhân b là b hàng, mỗi hàng có a chấm; tính tổng các hàng trước rồi mới rút thành phép nhân.',
    obj:'cái bút' },
  'dien-tich-don-vi': { model:'array', ten:'Diện tích là số ô vuông', cell:'square', rows:3, cols:5,
    khoi_dong:'Muốn lát kín nền phòng học thì cần biết chiều dài của phòng, hay cần biết bao nhiêu viên gạch?',
    chot:'Diện tích đếm bằng ô vuông đơn vị nên đơn vị là cm², dm², m²; hình chữ nhật là dài nhân rộng, đừng nhầm sang chu vi.',
    obj:'ô vuông' },
  'lam-tron': { model:'numline', ten:'Làm tròn số bằng tia số', nlMax:100, nlBase:10, nlValue:48,
    khoi_dong:'Mua món đồ giá 48 nghìn, cô đưa tờ 50 nghìn. Vì sao cả người bán và cô đều nói gọn là "gần 50 nghìn"?',
    chot:'Làm tròn là tìm mốc tròn gần nhất trên tia số; chữ số quyết định nằm ngay bên phải hàng đang làm tròn, từ 5 trở lên thì làm tròn lên.',
    obj:'vạch' },
  'hang-so': { model:'sticks', ten:'Giá trị theo hàng', tens:5, ones:3,
    khoi_dong:'Cô có 350 nghìn đồng và cô cũng có 350 đồng. Cả hai đều có chữ số 3 và 5, vì sao một số lớn gấp hơn nghìn lần số kia?',
    chot:'Cùng một chữ số nhưng đứng ở hàng khác nhau thì giá trị khác nhau; hàng bên trái luôn gấp 10 lần hàng ngay bên phải nó.',
    obj:'que tính' },
  'hinh-binh-hanh': { model:'shear', ten:'Diện tích hình bình hành', b:6, h:4, shear:2,
    khoi_dong:'Hình bình hành không phải hình chữ nhật. Vậy công thức dài nhân rộng còn dùng được không?',
    chot:'Cắt mảnh tam giác theo đường cao rồi ghép sang phía bên kia thành hình chữ nhật; đáy thành chiều dài và đường cao thành chiều rộng.',
    obj:'ô vuông' },
  'tat-ca': { model:'balance', ten:'Hai vế như hai đĩa cân', balL:3, balR:3,
    khoi_dong:'Một cái cân đang thăng bằng. Bỏ thêm 2 quả cân vào CẢ HAI đĩa thì cân sẽ thế nào?',
    chot:'Cộng hoặc trừ cả hai vế cùng một lượng thì cân vẫn thăng bằng; nhờ đó tìm được số còn thiếu mà không phải đoán thử.',
    obj:'quả cân' },
  'thoi-gian': { model:'clock', ten:'Đọc giờ, phút và khoảng thời gian', hour:8, minute:30,
    khoi_dong:'Kim dài chỉ số 6. Đó là 6 phút hay 30 phút?',
    chot:'Mỗi số trên mặt đồng hồ ứng với 5 phút; kim ngắn chỉ giờ, kim dài chỉ phút, còn khoảng thời gian là hiệu của hai mốc. Nhớ 1 giờ = 60 phút, không phải 100.',
    obj:'kim đồng hồ' },
  'goc': { model:'goc', ten:'Đo góc bằng thước nửa tròn', goc:60,
    khoi_dong:'Cánh cửa mở hé và cánh cửa mở toang. Góc nào lớn hơn, và làm sao biết nó lớn hơn bao nhiêu độ?',
    chot:'Góc vuông 90° là mốc so sánh: nhỏ hơn là góc nhọn, lớn hơn mà chưa thẳng là góc tù, đúng 180° là góc bẹt.',
    obj:'góc' },
  'the-tich': { model:'cube', ten:'Thể tích là số khối lập phương', cL:3, cW:2, cH:2,
    khoi_dong:'Một cái hộp phải xếp bao nhiêu khối cạnh 1 cm thì đầy kín?',
    chot:'Thể tích đếm bằng khối lập phương đơn vị nên đơn vị là cm³ hoặc m³; xếp kín một lớp đáy rồi nhân với số lớp.',
    obj:'khối 1 cm³' },
  'thap-phan': { model:'grid100', fmt:'decimal', g100:25, ten:'Số thập phân sinh ra từ lưới 100 ô',
    khoi_dong:'Một cái bánh chia thành 100 phần bằng nhau, ăn 25 phần. Nói gọn bằng MỘT số thì nói thế nào?',
    chot:'Phần mười, phần trăm, phần nghìn là các hàng đứng sau dấu phẩy; 25/100 viết là 0,25 và đọc là không phẩy hai mươi lăm.',
    obj:'ô vuông' },
  'phan-tram': { model:'grid100', fmt:'percent', g100:20, gia:200, ten:'Tỉ số phần trăm và bài toán giảm giá',
    khoi_dong:'Cái áo giá 200 nghìn được giảm 20%. Vậy được giảm bao nhiêu tiền và phải trả bao nhiêu?',
    chot:'Phần trăm của một số bằng số đó nhân với tỉ lệ rồi chia cho 100; số tiền phải trả bằng giá ban đầu trừ đi phần được giảm.',
    obj:'ô vuông' },
  'bieu-do-cot': { model:'bar', ten:'Biểu đồ cột và đường dóng sang trục giá trị',
    cats:['Táo','Cam','Xoài','Na'], danvi:'quả', b0:4, b1:7, b2:6, b3:5, barSel:1, dong:true,
    khoi_dong:'Hai cột cao gần bằng nhau. Làm sao biết cột nào cao hơn mà không đoán bằng mắt?',
    chot:'Kẻ một đường dóng ngang từ đỉnh cột sang trục giá trị rồi đọc đúng vạch; cấm ước lượng bằng mắt.',
    obj:'cột' },
  'bang-so-lieu': { model:'mean', ten:'Trung bình cộng — san đều cho bằng nhau',
    cats:['Tổ 1','Tổ 2','Tổ 3','Tổ 4'], danvi:'bông hoa', q0:7, q1:4, q2:6, q3:3, qSel:0, san:true,
    khoi_dong:'Bốn tổ hái được 7, 4, 6, 3 bông hoa. Nếu chia lại cho ĐỀU thì mỗi tổ có bao nhiêu bông?',
    chot:'Phải dóng đúng cả tên hàng và tên cột mới đọc được giá trị của một ô; số trung bình cộng bằng tổng chia cho số phần tử.',
    obj:'trung bình cộng' },
  'ti-so-tong-hieu': { model:'tape', ten:'Tìm hai số khi biết tổng và tỉ số',
    labels:['Em','Anh'], danvi:'viên bi', tpA:1, tpB:2, tpTong:30, tpShow:true,
    khoi_dong:'Hai anh em có tất cả 30 viên bi, số bi của anh gấp đôi số bi của em. Không đoán thử, làm sao chia đúng?',
    chot:'Chia tổng hoặc hiệu thành các phần bằng nhau theo tỉ số; giá trị một phần bằng tổng chia cho tổng số phần.',
    obj:'sơ đồ đoạn thẳng' },
  'hinh-thoi': { model:'rhomb', ten:'Diện tích hình thoi bằng hai đường chéo',
    rhD1:6, rhD2:4, rhGhep:true,
    khoi_dong:'Bốn tam giác của một hình thoi xếp lại với nhau thì thành hình gì?',
    chot:'Hai đường chéo của hình thoi vuông góc và cắt nhau tại trung điểm mỗi đường; ghép bốn tam giác thành hình chữ nhật nên diện tích là tích hai đường chéo chia 2.',
    obj:'đường chéo' },
  'phan-so-bang-nhau': { model:'fracbar', ten:'Hai phân số bằng nhau và rút gọn',
    fbN1:1, fbD1:2, fbN2:2, fbD2:4,
    khoi_dong:'Bạn An ăn 1/2 cái bánh, bạn Bình ăn 2/4 cái bánh cùng loại. Ai ăn nhiều hơn?',
    chot:'Hai phần tô trùng khít nhau trên hai băng bằng chiều dài là hai phân số bằng nhau; chia cả tử và mẫu cho cùng một số khác 0 thì giá trị không đổi.',
    obj:'phân số bằng nhau' },
  'quy-dong-mau': { model:'fracbar', ten:'Quy đồng mẫu số để so sánh hai phân số',
    fbN1:1, fbD1:3, fbN2:1, fbD2:4,
    khoi_dong:'Không có hình vẽ nào cả, làm sao biết 1/3 và 1/4 cái nào lớn hơn?',
    chot:'Muốn so sánh hai phân số khác mẫu thì phải chia lại cả hai trên cùng một trục; nhân cả tử và mẫu nên độ dài phần tô không thay đổi.',
    obj:'quy đồng mẫu' },
  'xac-suat': { model:'prob', ten:'Chắc chắn, có thể, không thể',
    pR:4, pB:0, pY:0, pAsk:1,
    khoi_dong:'Trong hộp kín chỉ có bóng đỏ. Nhắm mắt rút một quả. Có thể rút ra bóng xanh không?',
    chot:'Liệt kê hết các kết quả có thể rồi đếm kết quả thuận lợi; không có kết quả thuận lợi là không thể, mọi kết quả đều thuận lợi là chắc chắn.',
    obj:'khả năng' },
  'vuong-goc-song-song': { model:'lines', ten:'Hai đường vuông góc và hai đường song song',
    lnAng:15, lnExt:false,
    khoi_dong:'Ngay trong lớp mình, tìm hai vật song song với nhau và hai vật vuông góc với nhau?',
    chot:'Kéo dài mãi mà không gặp nhau là song song; gặp nhau và khít đúng góc của ê-ke là vuông góc.',
    obj:'hai đường thẳng' },
  'chia': { model:'groups', ten:'Chia đều và số dư', dvSo:17, dvNhom:5,
    khoi_dong:'17 cái kẹo chia đều cho 5 bạn. Còn thừa mấy cái và vì sao không chia tiếp được nữa?',
    chot:'Chia là phát lần lượt mỗi nhóm một đơn vị cho tới khi hết; phần còn lại không đủ cho mỗi nhóm một đơn vị nữa là số dư, và số dư luôn nhỏ hơn số chia.',
    obj:'băng chuyền' },
  'cong-tru-phan-so': { model:'fracops', ten:'Cộng trừ phân số cùng mẫu trên trục', foD:4, foN1:1, foN2:2, foOp:true,
    khoi_dong:'Ăn 1/4 cái bánh rồi ăn thêm 2/4 cái nữa. Làm sao nhìn một cái là thấy ngay 3/4?',
    chot:'Cùng mẫu số thì cộng hoặc trừ tử số và giữ nguyên mẫu; vượt quá một cái đầy thì viết thành hỗn số có phần nguyên.',
    obj:'trục phân số' },
  'bieu-do-tranh': { model:'pic', ten:'Biểu đồ tranh: một hình bằng mấy đơn vị', piU:5, piH:false, piSel:0, pi0:3, pi1:5, pi2:2, pi3:4,
    khoi_dong:'Biểu đồ vẽ 3 cái kẹo, nhưng chú giải ghi "1 hình = 5 cái". Vậy thực ra có mấy cái?',
    chot:'Mở khung chú giải ra đọc trước rồi mới đếm hình; số hình nhân với giá trị một hình, còn nửa hình thì tính nửa giá trị.',
    obj:'biểu đồ tranh' },
  'chuyen-dong': { model:'motion', ten:'Quãng đường, vận tốc, thời gian và hai xe ngược chiều', mtS:120, mtV1:40, mtV2:20, mtT:1,
    khoi_dong:'Hai xe đi ngược chiều từ hai đầu một con đường. Làm sao biết chúng gặp nhau ở chỗ nào?',
    chot:'Quãng đường bằng vận tốc nhân thời gian; hai chuyển động ngược chiều thì mỗi đơn vị thời gian khoảng cách ngắn đi đúng bằng tổng hai vận tốc.',
    obj:'con đường' },
  'ti-le-ban-do': { model:'scale', ten:'Tỉ lệ bản đồ và độ dài thật', scCm:3, scReal:10,
    khoi_dong:'Đo trên bản đồ được 3 cm. Ngoài đời thật con đường đó dài bao nhiêu?',
    chot:'Một xăng-ti-mét trên bản đồ ứng với một số mét thật ghi ở thước tỉ lệ; độ dài thật bằng số đo trên bản đồ nhân với hệ số tỉ lệ.',
    obj:'bản đồ' },
  'phan-so-cua-mot-so': { model:'fracof', ten:'Tìm phân số của một số', fcTotal:12, fcDen:3, fcTu:1,
    khoi_dong:'Một hòm có 12 đồng vàng, lấy ra 1/3 hòm. Lấy mấy đồng?',
    chot:'Chia số đó cho mẫu số để ra giá trị một phần, rồi nhân với tử số; phải chia thành nhóm bằng nhau trước rồi mới lấy phần.',
    obj:'hòm vàng' },
  'gap-giam-khau-phan': { model:'recipe', ten:'Gấp và giảm khẩu phần theo tỉ số nguyên liệu', rpBase:2, rpNew:6,
    khoi_dong:'Công thức nấu cho 2 người, nhưng nhà mình có 6 người ăn. Mỗi nguyên liệu phải làm gì?',
    chot:'Mọi nguyên liệu cùng nhân một hệ số thì tỉ số giữa chúng không đổi; hệ số bằng số khẩu phần mới chia cho số khẩu phần cũ.',
    obj:'nấu ăn' },
  'tan-ta-kg-can': { model:'units', ten:'Tấn, tạ, ki-lô-gam và cân hai đĩa', unL:3, unLu:3, unR:3, unRu:0,
    khoi_dong:'Một con voi và một túi đường. Vì sao không ai nói "con voi nặng 3 ki-lô-gam" dù số 3 rất nhỏ?',
    chot:'Một tấn bằng 10 tạ bằng 1000 kg; đổi đơn vị là nhân hoặc chia đúng 10 mỗi bậc, và phải đổi về cùng đơn vị trước khi so sánh.',
    obj:'cân nặng' },
  'thap-phan-can-bang': { model:'dec', ten:'So sánh số thập phân theo cột dấu phẩy', aU:0, a1:5, a2:0, a3:0, bU:0, b1:4, b2:8, b3:0,
    khoi_dong:'0,5 và 0,48: số nào lớn hơn, và vì sao nhiều chữ số hơn chưa chắc đã lớn hơn?',
    chot:'Xếp thẳng cột dấu phẩy rồi so từng hàng từ trái sang phải; thêm chữ số 0 vào cuối phần thập phân thì giá trị không đổi.',
    obj:'so sánh thập phân' },
  'chan-le': { model:'parity', ten:'Số chẵn số lẻ nhìn ở chữ số tận cùng', pn:15,
    khoi_dong:'Xếp 15 bạn của lớp mình thành từng đôi để múa. Có bạn nào phải đứng một mình không?',
    chot:'Chỉ chữ số tận cùng quyết định chẵn hay lẻ; ghép hết thành đôi là chẵn, còn một mình là lẻ.',
    obj:'xếp đôi múa' },
  'ba-dang-viet': { model:'threeforms', ten:'Ba dạng viết của cùng một giá trị', tfDI:0, tfN:1,
    khoi_dong:'1/2, 0,5 và 50% là một thứ hay là ba thứ khác nhau?',
    chot:'Phân số thập phân, số thập phân và phần trăm là ba cách viết của cùng một lượng; dóng ba băng trên một trục thì thấy chúng trùng khít.',
    obj:'cái bánh được nửa' },
  'bai-toan-nhieu-buoc': { model:'steps', ten:'Bài toán nhiều bước và sơ đồ đoạn thẳng',
    de:'Trường mua 3 hộp bút, mỗi hộp 12 chiếc, chia đều cho 4 tổ. Hỏi mỗi tổ mấy chiếc?',
    steps:[ {muc:'Số bút cả trường mua', phep:'3 × 12', donvi:'chiếc', kq:36},
            {muc:'Số bút mỗi tổ', phep:'36 : 4', donvi:'chiếc', kq:9} ],
    khoi_dong:'Một bài toán đố dài bốn dòng chữ. Làm sao biết phải tính cái gì trước?',
    chot:'Vẽ sơ đồ trước rồi mới tính; mỗi bước một phép tính kèm đơn vị, và đáp số nằm ở bước cuối cùng.',
    obj:'bài toán đố' },
  'so-sanh-sap-xep': { model:'numcmp', ten:'So sánh và sắp xếp số có nhiều chữ số', aLen:1, aHi:9, bLen:2, bHi:1,
    khoi_dong:'Hai bạn thi viết số lớn hơn: một bạn chỉ được viết 5 chữ số, một bạn được viết 6 chữ số. Chưa cần đọc hết số, ai chắc chắn thắng?',
    chot:'So sánh bắt đầu từ số chữ số rồi mới so từ hàng lớn nhất xuống; đừng nhìn chữ số đầu tiên mà kết luận ngay.',
    obj:'thi viết số' },
  'doc-bang-so-lieu': { model:'dtable', ten:'Đọc bảng số liệu không nhầm hàng, không nhầm cột',
    khoi_dong:'Trong bảng điểm của cả lớp, làm sao tìm đúng điểm của một bạn mà không đọc sang bạn ngồi bên cạnh?',
    chot:'Phải dóng đúng cả tên hàng và tên cột mới đọc được giá trị của một ô; số trung bình cộng bằng tổng chia cho số phần tử.',
    obj:'bảng điểm lớp', dtRow:0, dtCol:0 },
  'cong-tru': { model:'borrow', ten:'Cộng trừ có nhớ và có mượn, nhìn bằng bó que',
    khoi_dong:'Có 3 bó chục và 2 que lẻ. Muốn bớt đi 5 que thì làm thế nào khi số que lẻ không đủ để bớt?',
    chot:'Thiếu ở một hàng thì mượn một bó của hàng bên trái và bó đó tách thành đúng 10 que; nhớ và mượn phải ghi lại chứ không tính nhẩm rồi quên.',
    obj:'bó que tính', boT:3, boO:2, bsT:1, bsO:5 },
  'on-tap-toan-4': { model:'chooser', ten:'Ôn tập cuối lớp 4 trên bốn trạm vật thật', chSel:0,
    de:'Bài: "Hình chữ nhật dài 6cm, rộng 4cm. Tính diện tích." Bài này thuộc mạch nào — chọn đúng VẬT THẬT để thao tác.',
    khoi_dong:'Suốt năm lớp 4, chúng mình đã dùng những vật thật nào để học Toán?',
    chot:'Mỗi mạch kiến thức có một vật thật và một sơ đồ riêng; nhận ra bài thuộc mạch nào thì chọn đúng vật của mạch đó.',
    obj:'bốn trạm ôn tập',
    opts:[ { n:'Lưới ô vuông', d:'Diện tích là đếm ô vuông phủ kín → đúng mạch đo diện tích (6 × 4 = 24 ô).', ok:true },
      { n:'Bó que tính', d:'Bó que dùng cho giá trị hàng và cộng trừ có nhớ — không phải diện tích.', ok:false },
      { n:'Bánh phân số', d:'Bánh tròn để tô phân số — bài này không hỏi phần của một cái.', ok:false },
      { n:'Mặt đồng hồ', d:'Đồng hồ để đọc giờ – phút — không liên quan hình chữ nhật.', ok:false } ] },
  'boss-cong-thu': { model:'chooser', ten:'Tổng hợp chương: chọn đúng công thức trước khi tính', chSel:0,
    de:'Đề: "Hồ nước hình chữ nhật dài 8m, rộng 5m, người ta lót gạch kín đáy." Việc ĐẦU TIÊN phải làm gì?',
    khoi_dong:'Đọc xong đề bài, việc đầu tiên là tính luôn hay là nhận ra đề đang hỏi công thức nào?',
    chot:'Viết lại đúng công thức cần dùng rồi mới thế số; sai công thức thì tính cẩn thận đến mấy cũng ra đáp số sai.',
    obj:'bài toán hồ nước',
    opts:[ { n:'Nhận ra: cần DIỆN TÍCH đáy', d:'Lót kín đáy → hỏi diện tích = dài × rộng = 8 × 5 = 40 m², rồi mới tính số gạch.', ok:true },
      { n:'Tính (8 + 5) × 2', d:'Ra CHU VI miệng hồ (26 m) — lót đáy không cần đường bao.', ok:false },
      { n:'Tính 8 × 5 × 2', d:'Gấp đôi vô lý — hồ không có chiều cao trong đề.', ok:false },
      { n:'Cộng 8 + 5 ngay', d:'Không là công thức nào, chỉ là tổng hai cạnh.', ok:false } ] },
  'hinh-hoc-on-tap': { model:'chooser', ten:'Chu vi, diện tích, thể tích: chọn đúng công thức', chSel:0,
    de:'Hình LẬP PHƯƠNG cạnh 3cm. Đề hỏi THỂ TÍCH. Chọn đúng công thức (chú ý đơn vị).',
    khoi_dong:'Bốn hình đã học thì có bốn công thức khác nhau. Làm sao để không dùng nhầm?',
    chot:'Đo đủ số đo mà công thức cần rồi mới thế số; chu vi và diện tích khác đơn vị, diện tích và thể tích cũng khác đơn vị.',
    obj:'hộp quà hình lập phương',
    opts:[ { n:'3 × 3 × 3 = 27 cm³', d:'a³ — ba số đo của cùng hình, cho thể tích; đơn vị là cm³.', ok:true },
      { n:'3 × 3 = 9 cm²', d:'Ra DIỆN TÍCH một mặt (cm²), không phải thể tích.', ok:false },
      { n:'(3 + 3) × 2 = 12 cm', d:'Ra CHU VI một mặt (cm) — một chiều.', ok:false },
      { n:'3 × 12 = 36 cm', d:'Ra tổng độ dài 12 cạnh — đơn vị cm, không phải thể tích.', ok:false } ] },
  'on-tap-toan-5': { model:'chooser', ten:'Ôn tập cuối lớp 5: chọn chiến lược trước khi tính', chSel:0,
    de:'Đề: "May 5 bộ quần áo như nhau hết 14m vải. Hỏi may 8 bộ như thế hết mấy mét vải?" Chốt chiến lược nào rồi mới tính?',
    khoi_dong:'Một bài toán đố lớp 5 có tới ba cách làm. Làm sao biết cách nào nên dùng?',
    chot:'Chốt chiến lược trước khi tính: rút về đơn vị, dùng tỉ số hay vẽ sơ đồ đoạn thẳng; mọi bước phải nằm dọc theo chiến lược đã chọn.',
    obj:'xưởng may', chien_luoc:'là rút về đơn vị hay vẽ sơ đồ đoạn thẳng?',
    opts:[ { n:'Rút về đơn vị', d:'1 bộ = 14 : 5 = 2,8 m → 8 bộ = 2,8 × 8 = 22,4 m. Cặp đại lượng 1-1 nên rút về 1 trước.', ok:true },
      { n:'Sơ đồ đoạn thẳng tổng–tỉ', d:'Sơ đồ này cần BIẾT TỔNG hai lượng — đề không cho tổng, không dùng được.', ok:false },
      { n:'Đếm chia nhóm (phân số của một số)', d:'Không có chuyện "lấy một phần của một số" ở đây.', ok:false },
      { n:'Vẽ hình rồi đo', d:'Bài toán đại lượng, không phải hình học — vẽ hình không giúp ích.', ok:false } ] },
  'tien-viet-nam': { model:'money', ten:'Tiền Việt Nam: đếm ví và tính tiền thối',
    khoi_dong:'Cô mua bộ hộp bút giá 38 nghìn, rút ví đưa cô bán hàng một lúc mấy tờ tiền. Làm sao biết vừa đủ, phải thối lại, hay còn thiếu?',
    chot:'Đếm tiền theo TỪNG mệnh giá rồi cộng lại thành tổng; tổng lớn hơn giá thì phần hơn là tiền được thối, nhỏ hơn thì còn phải thêm.',
    obj:'bộ hộp bút 38 nghìn', mnC0:3, mnC1:2, mnC2:1, mnC3:1, mnSel:0, mnPrice:38000 },
  'dau-hieu-chia-het': { model:'divis', ten:'Dấu hiệu chia hết cho 2, 5, 3 và 9',
    khoi_dong:'Cô đố: số 84 có chia hết cho 2 không? Cho 5? Không cần đặt tính — nhìn vào đâu mà em trả lời được ngay?',
    chot:'Chia hết cho 2 và 5 chỉ cần nhìn CHỮ SỐ TẬN CÙNG (2: chẵn; 5: tận cùng 0 hoặc 5); còn chia hết cho 3 và 9 phải lấy TỔNG các chữ số, KHÔNG phải chữ số cuối.',
    obj:'số 84', dvT:8, dvU:4 },
  'bieu-do-hinh-quat': { model:'piechart', ten:'Biểu đồ hình quạt: sở thích của cả lớp',
    khoi_dong:'Cô chiếu một vòng tròn chia thành các quạt về môn thể thao cả lớp thích. Không cần đếm từng em — nhìn quạt, em nói ngay môn nào chiếm nhiều phần trăm nhất không?',
    chot:'Cả hình tròn là 100% của TỔNG số em; mỗi quạt bằng số em của nhóm CHIA cho tổng rồi nhân 100. Quạt càng to thì càng nhiều phần trăm — đừng nhìn quạt mà đoán số tuyệt đối khi chưa biết tổng.',
    obj:'biểu đồ sở thích của 20 em', pc0:10, pc1:5, pc2:3, pc3:2, pcSel:0 },
  'bieu-do-doan-thang': { model:'line', ten:'Biểu đồ đoạn thẳng: nhiệt độ trong một ngày',
    khoi_dong:'Cô đo nhiệt độ lớp mình lúc 6 giờ, 9 giờ, 12 giờ, 15 giờ, 18 giờ rồi nối năm điểm thành một đường. Nhìn đường đi LÊN hay XUỐNG, em biết lúc nào nóng nhất không?',
    chot:'Trục NGANG là thời gian, trục DỌC là nhiệt độ; đọc giá trị bằng cách dóng từ điểm ra trục, đừng nhầm hai trục. Đoạn đi lên = nhiệt độ tăng, đi xuống = giảm; điểm CAO NHẤT = nóng nhất.',
    obj:'biểu đồ nhiệt độ một ngày', lg0:20, lg1:24, lg2:31, lg3:29, lg4:22, lgR:2 },
  'dai-luong-s-v-t': { model:'svt', ten:'Đại lượng: tam giác Quãng đường – Vận tốc – Thời gian',
    khoi_dong:'Cô vẽ một tam giác: S ở trên chóp, v và t ở hai đáy. Che một ô đi là em đọc ra ngay phép tính. Xe chạy 40 km/giờ trong 3 giờ thì đi được bao xa?',
    chot:'S = v × t; muốn tìm v lấy S ÷ t, tìm t lấy S ÷ v. Che ô cần tìm trên tam giác để nhớ phép tính — hai ô còn lại cùng hàng thì NHÂN, khác hàng thì CHIA.',
    obj:'xe đi 40 km/giờ trong 3 giờ', svS:120, svV:40, svT:3, svAsk:0 },
  'hinh-tron': { model:'circle', ten:'Hình tròn: bán kính, đường kính, chu vi và diện tích',
    khoi_dong:'Một đồng xu tròn: đo từ tâm ra mép là BÁN KÍNH, đi suốt ngang qua tâm là ĐƯỜNG KÍNH gấp đôi. Chỉ cần biết bán kính, em tính được vòng quanh nó dài bao nhiêu và mặt nó rộng bao nhiêu không?',
    chot:'Đường kính d = 2 × bán kính r. Chu vi C = 2 × π × r = π × d. Diện tích S = π × r × r. Nhớ π ≈ 3,14 — và đừng lẫn bán kính với đường kính khi tính.',
    obj:'hình tròn bán kính 5', coR:5 },
  'dien-tich-tam-giac': { model:'tri', ten:'Diện tích hình tam giác: đáy × chiều cao rồi chia 2',
    khoi_dong:'Cô có một hình chữ nhật và cắt nó dọc theo đường chéo → được hai tam giác y hệt nhau. Vậy một tam giác bằng bao nhiêu phần của hình chữ nhật? Muốn tính diện tích tam giác, ta làm thế nào?',
    chot:'Diện tích tam giác = đáy × chiều cao ÷ 2. Sở dĩ có "÷ 2" vì hai tam giác giống hệt ghép lại mới thành hình chữ nhật đáy × cao. QUÊN CHIA 2 là lỗi hay gặp nhất.',
    obj:'tam giác đáy 10 cao 6', trB:10, trH:6 },
  'dien-tich-hinh-thang': { model:'trap', ten:'Diện tích hình thang: (đáy lớn + đáy nhỏ) × chiều cao ÷ 2',
    khoi_dong:'Cô có một hình thang (đáy trên ngắn, đáy dưới dài). Nếu cô quay một hình thang GIỐNG HỆT rồi áp vào cạnh nghiêng, hai hình ghép thành một hình bình hành. Hình bình hành đó có đáy bằng bao nhiêu, và hình thang chiếm mấy phần của nó?',
    chot:'Diện tích hình thang = (đáy lớn + đáy nhỏ) × chiều cao ÷ 2. Sở dĩ CỘNG hai đáy rồi chia 2 vì hai hình thang giống hệt ghép thành hình bình hành đáy (a + b). Phải CỘNG hai đáy TRƯỚC khi nhân chiều cao, rồi mới chia 2.',
    obj:'hình thang đáy lớn 12, đáy nhỏ 6, cao 5', tpA:12, tpB:6, tpH:5 },
  'dien-tich-hinh-hop': { model:'sa', ten:'Diện tích xung quanh & toàn phần của hình hộp chữ nhật',
    khoi_dong:'Một cái hộp quà hình chữ nhật. Nếu cô dán giấy quanh 4 mặt XUNG QUANH rồi mới dán thêm NẮP và ĐÁY, em cần giấy cho mấy mặt mỗi lần? Diện tích xung quanh khác diện tích toàn phần ở chỗ nào?',
    chot:'Diện tích XUNG QUANH = (độ dài + độ rộng) × 2 × chiều cao (chỉ 4 mặt bên). Diện tích TOÀN PHẦN = xung quanh + 2 × (dài × rộng) (thêm nắp và đáy). ĐỪNG nhầm: toàn phần = xung quanh CỘNG hai mặt đáy.',
    obj:'hộp dài 6 rộng 4 cao 3', saA:6, saB:4, saC:3 },
  'thu-tu-tinh': { model:'order', ten:'Thứ tự thực hiện các phép tính',
    khoi_dong:'Cô viết 2 + 3 × 4 lên bảng. Hai bạn tính ra hai kết quả khác nhau: một bạn nói 20, một bạn nói 14. Ai đúng? Vì sao cùng một biểu thức mà ra hai số — họ làm theo thứ tự nào?',
    chot:'Thứ tự: có DẤU NGOẶC thì làm TRONG NGOẶC trước; không có ngoặc thì làm × và ÷ TRƯỚC, rồi mới đến + và −. Cùng các số 2, 3, 4: 2 + 3 × 4 = 14 (× trước), nhưng (2 + 3) × 4 = 20 (ngoặc trước). ĐỪNG đọc bừa từ trái sang phải.',
    obj:'2 + 3 × 4', ordA:2, ordB:3, ordC:4, ordK:0 },
  'chu-vi-dien-tich-hcn': { model:'rect', ten:'Chu vi và diện tích hình chữ nhật',
    khoi_dong:'Một cái sân trường hình chữ nhật. Muốn QUANG RÀO quanh sân thì ta cần biết độ dài đường nào? Muốn LÁT GẠK kín mặt sân thì ta cần biết độ lớn nào? Hai cái đó có giống nhau không?',
    chot:'CHU VI = độ dài đường bao QUANH hình = (dài + rộng) × 2, đo bằng cm (đơn vị dài). DIỆN TÍCH = độ lớn MẶT phủ kín hình = dài × rộng, đo bằng cm² (số ô vuông 1 cm). Cùng một hình chữ nhật nhưng là HAI đại lượng khác nhau — đừng lấy cái này trả lời cho câu hỏi của cái kia.',
    obj:'sân dài 6 rộng 4', rcA:6, rcB:4 },
  'chia-phan-so-cho-so-tu-nhien': { model:'fracdiv', ten:'Chia một phân số cho số tự nhiên',
    khoi_dong:'Mẹ cắt cho Hai chị em ăn 3/4 cái bánh. Giờ chị chia đều phần bánh đó cho 2 em. Mỗi em được bao nhiêu phần của CẢ cái bánh? Có phải lấy 3 chia 2 không, hay làm cách khác?',
    chot:'Muốn chia một phân số cho một số tự nhiên (khác 0), ta GIỮ NGUYÊN tử số rồi NHÂN mẫu số với số đó: a/b ÷ n = a/(b × n). Lí do: chia phần đã tô ra n phần bằng nhau làm MỖI Ô NHỎ ĐI n lần (mẫu × n), còn số ô tô vẫn là a.',
    obj:'3/4 cái bánh chia cho 2 em', fdNum:3, fdDen:4, fdDiv:2 },
  'nhan-chia-10-100-1000': { model:'dotshift', ten:'Nhân · chia số thập phân với 10, 100, 1000',
    khoi_dong:'Cô có số 12,34. Nếu nhân nó với 10, các chữ số 1, 2, 3, 4 có đổi đi không, hay chỉ có dấu phẩy là dời chỗ? Dời sang bên nào, dời mấy chữ số?',
    chot:'Nhân số thập phân với 10, 100, 1000… ta DỊCH dấu phẩy sang PHẢI đúng số chữ số 0 của số ấy (10→1 chữ số, 100→2, 1000→3); chia thì DỊCH sang TRÁI bấy nhiêu chữ số. Thiếu chữ số thì VIẾT THÊM số 0. Thứ tự các chữ số KHÔNG bao giờ thay đổi — chỉ dấu phẩy dời chỗ.',
    obj:'12,34 nhân 10', dsWhich:0, dsK:1 },
  'cong-tru-phan-so-khac-mau': { model:'fracdiff', ten:'Cộng · trừ hai phân số khác mẫu số',
    khoi_dong:'Cô có 1/2 băng giấy màu vàng và 1/3 băng giấy màu xanh (hai băng dài bằng nhau). Đem tô lại rồi cộng thì được bao nhiêu phần của cả băng? Có phải lấy 1+2 tử và 2+3 mẫu thành 2/5 không?',
    chot:'Muốn cộng (hoặc trừ) hai phân số KHÁC mẫu số, ta phải QUY ĐỒNG về CÙNG một mẫu số trước (thông thường lấy BCNN của hai mẫu), rồi chỉ CỘNG/TRỪ hai TỬ số, GIỮ NGUYÊN mẫu chung. TUYỆT đối không cộng cả mẫu: 1/2 + 1/3 = 3/6 + 2/6 = 5/6, KHÔNG phải 2/5.',
    obj:'1/2 + 1/3', fmN1:1, fmD1:2, fmN2:1, fmD2:3, fmOp:1 },
  'nhan-hai-so-thap-phan': { model:'decarea', ten:'Nhân hai số thập phân (lưới diện tích)',
    khoi_dong:'Cô có một ô vuông biểu diễn số 1, chia thành 100 ô nhỏ. 0,3 là tô 3 HÀNG, 0,4 là tô 4 CỘT. Chỗ vừa thuộc hàng vừa thuộc cột (phần giao) là mấy ô? Đó chính là 0,3 × 0,4. Vì sao tích lại BÉ hơn cả hai thừa số?',
    chot:'Khi nhân hai số thập phân, ta bỏ dấu phẩy, nhân như số tự nhiên, rồi ĐẾM xem cả hai thừa số có bao nhiêu chữ số thập phân để tách bấy nhiêu chữ số (từ phải sang) ở tích. 0,3 (1 chữ số) × 0,4 (1 chữ số) → tích có 1 + 1 = 2 chữ số thập phân = 0,12. Nhân hai số nhỏ hơn 1 thì tích BÉ đi, không lớn lên.',
    obj:'0,3 nhân 0,4', daM:3, daN:4 },
  'cong-tru-so-thap-phan': { model:'decadd', ten:'Cộng · trừ hai số thập phân (thẳng dấu phẩy)',
    khoi_dong:'Cô có hai dải ruy băng dài 3,4 dm và 2,5 dm. Nối hai dải lại thì được dài bao nhiêu đề-xi-mét? Có phải chỉ cần lấy 34 + 25 = 59 rồi… lúng túng không biết dấu phẩy đặt ở đâu? Vì sao khi tính phải đặt hai DẤU PHẨY THẲNG HÀNG nhau?',
    chot:'Muốn cộng (hay trừ) hai số thập phân, ta viết sao cho các DẤU PHẨY THẲNG HÀNG nhau (đơn vị dưới đơn vị, phần mười dưới phần mười), rồi cộng/trừ như số tự nhiên, cuối cùng viết dấu phẩy của kết quả THẲNG HÀNG với các dấu phẩy bên trên. Nhớ: 10 phần mười = 1 đơn vị, nên khi tổng phần mười ≥ 10 ta NHỚ 1, khi phần mười không đủ trừ ta MƯỢN 1 của đơn vị.',
    obj:'3,4 + 2,5', dcAW:3, dcAT:4, dcBW:2, dcBT:5, dcOp:1 },
  'chia-so-tu-nhien-ra-so-thap-phan': { model:'natdivdec', ten:'Chia số tự nhiên cho số tự nhiên ra thương thập phân',
    khoi_dong:'Có 7 chiếc bánh chia đều cho 2 bạn. Mỗi bạn lấy được 3 cái nguyên, còn THỪA 1 cái. Em nói "3 dư 1" — nhưng chia TIẾP cái thừa đó cho 2 bạn thì được bao nhiêu nữa? Làm sao để thương không còn là "dư" mà thành một số thập phân?',
    chot:'Khi chia số tự nhiên mà còn dư, ta viết DẤU PHẨY vào thương, rồi THÊM CHỮ SỐ 0 vào bên phải phần dư và chia tiếp; cứ thế đến khi không còn dư (hoặc đến số chữ số thập phân muốn). 7 : 2 = 3,5 vì còn dư 1 → thêm 0 thành 10, 10 : 2 = 5 (phần mười). Không được dừng lại viết "3 (dư 1)" khi đề bài cần thương là số thập phân.',
    obj:'7 : 2', ndA:7, ndB:2 },
  'don-vi-do-do-dai': { model:'lenunits', ten:'Bảng đơn vị đo độ dài (km · hm · dam · m · dm · cm · mm)',
    khoi_dong:'Cái bảng lớp dài 3 mét. Bạn nói "3 mét", bạn khác nói "300 xăng-ti-mét", bạn nữa lại nói "3000 mi-li-mét". Cùng một cái bảng mà sao số khác nhau to đùng thế? Đổi từ mét sang xăng-ti-mét thì ta NHÂN hay CHIA, và nhân bao nhiêu lần?',
    chot:'Bảng đơn vị đo độ dài từ lớn đến bé: km, hm, dam, m, dm, cm, mm. Hai đơn vị LIỀN NHAU luôn hơn kém nhau đúng 10 lần. Đổi từ đơn vị LỚN sang đơn vị BÉ (đi XUỐNG) thì NHÂN thêm 10 cho mỗi bậc; đổi từ BÉ sang LỚN (đi LÊN) thì CHIA 10 cho mỗi bậc. Đặc biệt 1 km = 1000 m, 1 m = 10 dm = 100 cm = 1000 mm.',
    obj:'3 m', luNum:3, luUnit:3 },
  'don-vi-do-dien-tich': { model:'areaunits', ten:'Bảng đơn vị đo diện tích (km² · hm² · dam² · m² · dm² · cm² · mm²)',
    khoi_dong:'Cô giáo nói nền lớp rộng 40 mét VUÔNG. Bạn Lan lát viên gạch 1 đề-xi-mét vuông. Lan đoán cần 400 viên vì "1 m = 10 dm". Nhưng nền lớp lát kín thì đếm ra 4000 viên! Vì sao đơn vị DIỆN TÍCH lại nhảy nhiều hơn đơn vị ĐỘ DÀI như vậy?',
    chot:'Bảng đơn vị đo diện tích từ lớn đến bé: km², hm², dam², m², dm², cm², mm². Hai đơn vị DIỆN TÍCH LIỀN NHAU hơn kém nhau 100 lần (vì 1 m = 10 dm nên 1 m² = 10 × 10 = 100 dm²). Muốn đổi từ đơn vị LỚN sang BÉ thì NHÂN 100 cho mỗi bậc, từ BÉ sang LỚN thì CHIA 100 cho mỗi bậc. Chú ý: diện tích nhảy ×100, KHÔNG phải ×10 như độ dài.',
    obj:'1 m²', auNum:1, auUnit:3 },
  'don-vi-do-the-tich': { model:'volunits', ten:'Bảng đơn vị đo thể tích (m³ · dm³ · cm³)',
    khoi_dong:'Một cái hộp sữa ghi 1 lít. Cô bảo 1 lít đúng bằng 1 đề-xi-mét khối. Bạn Bin đổ hộp sữa đó vào đầy các viên kẹo hình lập phương cạnh 1 xăng-ti-mét, đếm ra 1000 viên chứ không phải 100! Vì sao đơn vị THỂ TÍCH lại nhảy gấp 1000 lần, còn diện tích chỉ 100, độ dài chỉ 10?',
    chot:'Bảng đơn vị đo thể tích từ lớn đến bé: m³, dm³, cm³. Hai đơn vị THỂ TÍCH LIỀN NHAU hơn kém nhau 1000 lần (vì cạnh ×10 ở cả BA chiều nên 1 dm³ = 10 × 10 × 10 = 1000 cm³). Muốn đổi từ đơn vị LỚN sang BÉ thì NHÂN 1000 cho mỗi bậc, từ BÉ sang LỚN thì CHIA 1000. Đặc biệt 1 dm³ = 1 lít, 1 m³ = 1000 dm³ = 1000 lít. Chú ý: thể tích nhảy ×1000, KHÁC diện tích (×100) và độ dài (×10).',
    obj:'1 m³', vuNum:1, vuUnit:0 },
  'ti-le-thuan': { model:'prop', ten:'Hai đại lượng tỉ lệ thuận (y = k·x)',
    khoi_dong:'Một cái bút giá 3 nghìn. Mua 1 bút hết 3 nghìn, 2 bút hết 6 nghìn, 3 bút hết 9 nghìn. Số bút tăng thì số tiền cũng tăng theo. Hai cái đó "tỉ lệ thuận" với nhau nghĩa là thế nào — có phải cộng thêm mãi không, hay nhân lên?',
    chot:'Hai đại lượng tỉ lệ thuận khi đại lượng này gấp (hoặc rút đi) bao nhiêu LẦN thì đại lượng kia gấp (hoặc rút đi) đúng BẤY NHIÊU LẦN. Luôn có y = k·x với k không đổi (gọi là hệ số tỉ lệ). Thương y : x không đổi. Đồ thị của hai đại lượng tỉ lệ thuận là một ĐƯỜNG THẲNG đi qua gốc 0. CHÚ Ý: tỉ lệ thuận là NHÂN/GẤP, không phải CỘNG thêm.',
    obj:'x = 2', prK:3, prX:2 },
  'ti-le-nghich': { model:'inprop', ten:'Hai đại lượng tỉ lệ nghịch (x·y = A)',
    khoi_dong:'Chia 12 cái kẹo cho các bạn. 1 bạn thì được 12 cái, 2 bạn mỗi bạn 6 cái, 3 bạn mỗi bạn 4 cái… Càng nhiều bạn thì mỗi bạn càng nhận ÍT đi. Số bạn và số kẹo mỗi bạn "tỉ lệ nghịch" — nghĩa là cái gì ở đây KHÔNG đổi?',
    chot:'Hai đại lượng tỉ lệ nghịch khi đại lượng này gấp lên bao nhiêu LẦN thì đại lượng kia RÚT đi đúng BẤY NHIÊU LẦN. Luôn có x · y = A với A không đổi (gọi là tích không đổi), hay y = A : x. TÍCH x·y không đổi. Đồ thị của hai đại lượng tỉ lệ nghịch là một ĐƯỜNG CONG đi xuống, KHÔNG đi qua gốc. CHÚ Ý: khác tỉ lệ thuận (ở đó THƯƠNG y:x không đổi, đồ thị là đường thẳng qua gốc).',
    obj:'x = 2', inK:12, inX:2 },
  'don-vi-do-thoi-gian': { model:'timeunits', ten:'Bảng đơn vị đo thời gian (giờ · phút · giây)',
    khoi_dong:'Mặt đồng hồ có 12 số nhưng quanh viền là 60 vạch nhỏ. Kim phút đi hết MỘT vòng thì kim giờ nhích đúng 1 bước — nghĩa là 1 giờ = 60 phút. Khác hẳn mét hay ki-lô-gam (nhảy ×10), thời gian nhảy ×60. Vì sao lại là 60? Và "1 giờ rưỡi" là 1 giờ 30 phút hay 1 giờ 50 phút?',
    chot:'Bảng đơn vị đo thời gian: 1 thế kỉ = 100 năm, 1 ngày = 24 giờ, 1 giờ = 60 phút, 1 phút = 60 giây. Mỗi bậc thời gian liền nhau hơn kém NHAU 60 LẦN (KHÔNG phải 10 hay 100). CHÚ Ý lỗi kinh điển: 1,5 giờ = 1 giờ 30 phút (vì 0,5 giờ = 60 : 2 = 30 phút), KHÔNG phải 1 giờ 50 phút. Đổi thời gian phải nhớ số 60, không được áp dụng quy tắc ×10 của số thập phân.',
    obj:'1 giờ 30 phút', tuNum:2, tuUnit:0 },
  'hon-so': { model:'mixed', ten:'Hỗn số (đổi giữa phân số và hỗn số)',
    khoi_dong:'Cô có 5 MẢNH bánh, mỗi cái bánh được cắt thành 3 phần bằng nhau. Ghép 3 mảnh lại thì thành đúng 1 cái bánh nguyên. Hỏi với 5 mảnh ấy cô ghép được mấy cái bánh nguyên và còn thừa mấy mảnh? Vì sao 5/3 không phải là "5 cái bánh" mà là "1 cái và 2/3 cái" — hỗn số là gì?',
    chot:'Hỗn số gồm một SỐ TỰ NHIÊN (phần nguyên) đứng trước và một PHÂN SỐ bé hơn 1 (phần phân số) đứng sau, ví dụ 2 1/3. Một phân số LỚN HƠN 1 đổi sang hỗn số bằng cách: lấy TỬ số CHIA MẪU số — thương là phần nguyên, số dư là tử của phần phân số, MẪU số GIỮ NGUYÊN. Ví dụ 5/3: 5 : 3 = 1 dư 2 nên 5/3 = 1 2/3. Ngược lại đổi hỗn số về phân số: lấy phần nguyên × mẫu số rồi cộng tử số. CHÚ Ý: 5/3 KHÔNG phải là 5 1/3 — phải CHIA 5 cho 3 trước.',
    obj:'5/3', mxTop:5, mxDen:3 },
  'phan-so-thap-phan': { model:'decfrac', ten:'Phân số thập phân ↔ số thập phân (bảng hàng giá trị)',
    khoi_dong:'Cô có một băng giấy chia 10 phần bằng nhau, tô 7 phần. Viết là 7/10. Nhưng trên bảng hàng giá trị thì 7 phần đó nằm ở HÀNG NÀO sau dấu phẩy? Vì sao 7/10 = 0,7 mà 7/100 lại là 0,07 chứ không phải 0,7?',
    chot:'Phân số có MẪU là 10, 100, 1000 gọi là PHÂN SỐ THẬP PHÂN, và nó viết thẳng thành SỐ THẬP PHÂN: tử số đặt vào đúng HÀNG của mẫu — mẫu 10 → chữ số ở hàng PHẦN MƯỜI, mẫu 100 → hàng PHẦN TRĂM, mẫu 1000 → hàng PHẦN NGHÌN. Thiếu hàng nào thì viết CHỮ SỐ 0 ở hàng đó (7/1000 = 0,007). Ở tận cùng bên phải, thêm/bớt chữ số 0 KHÔNG đổi giá trị (0,5 = 0,50 = 50/100).',
    obj:'7/10', dfExp:1, dfNum:7 },
  'nhan-so-0': { model:'zeromult', ten:'Nhân nhẩm với số có chữ số 0 ở tận cùng',
    khoi_dong:'Cô bảo 30 × 4. Nhiều em nhảy ngay vào tính 30 × 4 theo cột dọc rất lâu. Nhưng có một cách NHẨM nhanh: tạm BỎ chữ số 0 ở tận cùng, tính 3 × 4, rồi viết lại chữ số 0 đó. Vì sao làm thế được? Kết quả là bao nhiêu và vì sao KHÔNG phải 12?',
    chot:'Khi nhân với số có chữ số 0 ở tận cùng: ta TẠM BỎ các chữ số 0, nhân PHẦN KHÁC 0 với nhau, rồi VIẾT LẠI đúng BẤY NHIÊU chữ số 0 vào tận cùng tích. Số 0 ở tận cùng chỉ "to gấp 10, 100…", không làm thay đổi phép nhân cơ bản. Ví dụ 30 × 4: bỏ 1 chữ số 0 → 3 × 4 = 12 → viết lại 1 chữ số 0 → 120. CHÚ Ý: quên viết lại chữ số 0 là ra 12 (sai), viết dư là ra 1 200 (cũng sai).',
    obj:'30 × 4', zmMant:3, zmZeros:1, zmB:4 },
  'cong-nhom-tron': { model:'addgroup', ten:'Cộng bằng cách nhóm tạo tròn chục (giao hoán + kết hợp)',
    khoi_dong:'Cô viết 27 + 43 + 15. Nếu cộng lần lượt từ trái sang thì 27 + 43 đã phải nhớ lung tung. Nhưng nhìn chữ số tận cùng: 7 và 3 ghép lại vừa đủ thành 10! Vì sao nên ĐỔI CHỖ các số hạng, ghép 27 với 43 thành 70 trước rồi mới cộng 15? Kết quả ra bao nhiêu?',
    chot:'Muốn cộng nhiều số cho nhanh, ta vận dụng TÍNH CHẤT GIAO HOÁN và KẾT HỢP của phép cộng: ĐỔI CHỖ để các số hạng có chữ số tận cùng BÙ NHAU THÀNH 0 đứng cạnh nhau, rồi THÊM NGOẶC để cộng chúng trước tạo số TRÒN CHỤC (hoặc tròn trăm). Ví dụ 27 + 43 + 15 = (27 + 43) + 15 = 70 + 15 = 85. Tổng KHÔNG ĐỔI dù ta đổi thứ tự và cách nhóm.',
    obj:'27 + 43 + 15', agA:27, agB:43, agC:15 },
  'hieu-va-ti': { model:'diffratio', ten:'Tìm hai số khi biết HIỆU và TỈ số của hai số đó',
    khoi_dong:'Hai rổ cam hơn nhau đúng 24 quả. Rổ lớn theo tỉ số 5 phần, rổ bé 2 phần (5 : 2). Vì sao 24 quả đó ứng với (5 − 2) = 3 PHẦN, chứ KHÔNG phải 5 + 2 = 7 phần? Mỗi phần là bao nhiêu quả, rổ lớn và rổ bé có mấy quả?',
    chot:'Dạng toán TÌM HAI SỐ KHI BIẾT HIỆU và TỈ SỐ: vẽ sơ đồ — số lớn gồm a phần bằng nhau, số bé gồm b phần (a lớn hơn b). HIỆU đúng bằng (a − b) phần, nên GIÁ TRỊ MỘT PHẦN = HIỆU : (a − b). Số bé = b × một phần, số lớn = a × một phần. CHÚ Ý: phải chia cho HIỆU SỐ PHẦN (a − b), KHÔNG phải TỔNG số phần (a + b) — đó là điểm khác căn bản so với dạng TỔNG và tỉ số.',
    obj:'hiệu 24, tỉ 5 : 2', drBig:5, drSmall:2, drDiff:24 },
  'tong-va-hieu': { model:'sumdiff', ten:'Tìm hai số khi biết TỔNG và HIỆU của hai số đó',
    khoi_dong:'Hai tấm vải dài tổng cộng 96 m, tấm thứ nhất dài hơn tấm thứ hai 12 m. Vì sao bớt 12 m ở tấm dài thì hai tấm bằng nhau và mỗi tấm còn (96 − 12) : 2 = 42 m? Hai tấm vải dài bao nhiêu mét?',
    chot:'Dạng toán TÌM HAI SỐ KHI BIẾT TỔNG và HIỆU: Số bé = (TỔNG − HIỆU) : 2, Số lớn = (TỔNG + HIỆU) : 2. Giải thích: nếu BỚT đi phần hơn (HIỆU) ở số lớn thì hai số bằng nhau và đều bằng số bé, lúc đó tổng mới = TỔNG − HIỆU = 2 × số bé. CHÚ Ý: (tổng + hiệu) : 2 ra số LỚN, (tổng − hiệu) : 2 ra số BÉ — đừng đổi ngược.',
    obj:'tổng 96, hiệu 12', sdSum:96, sdDiff:12 },
  'day-so-cach-deu': { model:'seq', ten:'Dãy số cách đều — tìm số hạng thứ n',
    khoi_dong:'Dãy số 3, 7, 11, 15, … mỗi số hơn số liền trước 4 đơn vị. Vì sao muốn tìm số hạng thứ 12 ta lấy 3 + (12 − 1) × 4 = 47, chứ KHÔNG phải 12 × 4 = 48?',
    chot:'Dãy số CÁCH ĐỀU: Số hạng thứ n = SỐ ĐẦU + (n − 1) × CÔNG SỐ. Từ số đầu đến số thứ n có đúng (n − 1) BƯỚC nhảy, mỗi bước thêm đúng công số d. CHÚ Ý: phải nhân (n − 1), không phải n — số đầu chưa tính là một bước. Số số hạng từ a đến b: (b − a) : d + 1.',
    obj:'dãy 3, 7, 11, … ; số hạng thứ 12', sqA:3, sqD:4, sqN:12 },
  'rut-gon-phan-so': { model:'psimp', ten:'Rút gọn phân số — chia cả tử và mẫu cho cùng một số',
    khoi_dong:'Lớp có 18 bạn, trong đó 12 bạn thích vẽ. Vì sao nói "12/18 = 2/3" được — cả tử và mẫu cùng chia cho 6 thì giá trị phần chỉ số bạn thích vẽ có đổi không?',
    chot:'RÚT GỌN phân số: chia cả TỬ SỐ và MẪU SỐ cho cùng một số (khác 0) thì phân số KHÔNG đổi giá trị. Rút đến khi tử và mẫu không còn chia chung được nữa (ƯCLN = 1) gọi là phân số TỐI GIẢN — muốn nhanh thì chia một lần cho ƯCLN. CHÚ Ý: phải chia CẢ HAI; chỉ chia tử hoặc chỉ chia mẫu là SAI.',
    obj:'rút gọn 12/18', psN:12, psD:18 },
  'so-sanh-hai-phan-so': { model:'fraccmp', ten:'So sánh hai phân số khác mẫu số',
    khoi_dong:'Hai thanh bánh dài bằng nhau. Em thứ nhất ăn 3/4 thanh, em thứ hai ăn 5/6 thanh. Mẫu số khác nhau (4 và 6) thì so thế nào — có được lấy 3 so với 5 không?',
    chot:'SO SÁNH hai phân số KHÁC MẪU: KHÔNG được so tử số với tử số. Cách 1 — quy đồng về CÙNG mẫu rồi so tử. Cách nhanh 2 — NHÂN CHÉO: a/b so với c/d thì so a×d với c×b; tích nào lớn hơn thì phân số đó lớn hơn. CHÚ Ý: nhân chéo đúng là đưa cả hai về cùng mẫu tích (b×d) rồi tử trở thành a×d và c×b.',
    obj:'so sánh 3/4 và 5/6', fcA:3, fcB:4, fcC:5, fcD:6 },
  'bieu-thuc-chua-chu': { model:'expr', ten:'Biểu thức chứa chữ — thay chữ bằng số rồi tính',
    khoi_dong:'Cô viết "a + 5". Khi a = 8 thì kết quả là bao nhiêu? Vì sao "a + 5" chưa tính được ngay mà phải đợi người ta nói a bằng mấy?',
    chot:'BIỂU THỨC CHỨA CHỮ (a, b, …) là một cách viết GỌI TÊN cho số chưa biết; nó chỉ có GIÁ TRỊ khi ta THAY chữ bằng một số cụ thể. Cùng một chữ xuất hiện nhiều lần phải lấy CÙNG một giá trị. Muốn tính giá trị biểu thức: thay số vào chỗ chữ, rồi làm theo thứ tự phép tính (× ÷ trước, + − sau, có ngoặc thì ngoặc trước).',
    obj:'tính a + b, a × b với a = 7, b = 5', exA: 7, exB: 5 },
  'nhan-nham-11-25-99': { model:'nhamsam', ten:'Nhân nhẩm với 11, 25, 99 — biến về ×10 · ×100 rồi cộng/trừ',
    khoi_dong:'Tính 24 × 11 mà không đặt tính. Vì sao 24 × 11 = 240 + 24 = 264 — chỉ cần "thêm một cái 24 nữa" vào số tròn chục?',
    chot:'NHÂN NHẨM mẹo: ×11 = ×10 rồi CỘNG chính nó (a×11 = a0 + a). ×25 = ×100 rồi CHIA 4 (a×25 = a00 : 4). ×99 = ×100 rồi TRỪ chính nó (a×99 = a00 − a). Gốc của mẹo là đổi số khó nhân (11, 25, 99) về số tròn (10, 100) mà em đã biết, rồi hiệu chỉnh bằng đúng phần thừa/thiếu. CHÚ Ý: ×11 KHÔNG phải "viết a rồi thêm 0" — phải cộng thêm chính a.',
    obj:'nhẩm 24 × 11', nhA: 24, nhM: 0 },
  'tinh-chat-nhan': { model:'multprop', ten:'Tính chất giao hoán và kết hợp của phép nhân — nhóm ra tròn chục/trăm để tính nhanh',
    khoi_dong:'Tính 25 × 7 × 4 mà không đặt tính. Vì sao ta ĐẢO chỗ 4 lên cạnh 25 rồi tính (25 × 4) × 7 = 100 × 7 = 700, nhanh hơn nhiều so với 25 × 7 = 175 rồi × 4?',
    chot:'GIAO HOÁN: đổi chỗ các thừa số thì tích KHÔNG đổi (a × b = b × a). KẾT HỢP: được nhóm hai thừa số lại trước (a × b) × c = a × (b × c). Mẹo tính nhanh: DÙNG giao hoán để KÉO hai thừa số nhân ra tròn chục/round trăm (25 với 4 → 100; 125 với 8 → 1000; 5 với số chẵn → tròn 10) đứng cạnh nhau, rồi KẾT HỢP nhóm chúng tính trước. Đáp số CUỐI luôn bằng nhau dù nhóm cách nào — chính hai tính chất này cho phép làm thế.',
    obj:'tính nhanh 25 × 7 × 4', mA: 25, mB: 7, mC: 4 },
  'lam-tron-so-thap-phan': { model:'decrond', ten:'Làm tròn số thập phân đến hàng đơn vị / phần mười',
    khoi_dong:'Làm tròn 3,47 đến hàng phần mười được số nào? Vì sao chỉ cần nhìn chữ số 7 (hàng phần trăm) mà KHÔNG cần để ý các chữ số còn lại?',
    chot:'LÀM TRÒN SỐ THẬP PHÂN làm giống số tự nhiên: chọn HÀNG cần làm tròn, rồi chỉ nhìn CHỮ SỐ NGAY BÊN PHẢI nó. Chữ số đó từ 5 trở lên thì CỘNG 1 vào hàng đang làm tròn, nhỏ hơn 5 thì GIỮ; sau đó BỎ hết các chữ số bên phải. Làm tròn đến phần mười thì còn 1 chữ số sau dấu phẩy, đến đơn vị thì mất hết phần thập phân. KHÔNG làm tròn dây chuyền nhiều bước.',
    obj:'làm tròn 3,47 đến hàng phần mười', rU: 3, rT: 4, rH: 7, rTar: 1 },
  'nhan-hai-chu-so-dien-tich': { model:'areamult', ten:'Nhân số có hai chữ số bằng mô hình diện tích (tích riêng phần)',
    khoi_dong:'Tính 23 × 14. Thay vì đặt tính ngay, ta vẽ HÌNH CHỮ NHẬT 23 × 14 rồi CHIA nó thành 4 ô theo chục và đơn vị: 20×10, 20×4, 3×10, 3×4. Vì sao cộng 4 ô lại thì bằng đúng 23 × 14?',
    chot:'MÔ HÌNH DIỆN TÍCH (tích riêng phần): tách mỗi thừa số thành chục + đơn vị, 23 × 14 = (20 + 3) × (10 + 4). Vẽ hình chữ nhật chia 4 ô, diện tích từng ô là 20×10 = 200, 20×4 = 80, 3×10 = 30, 3×4 = 12. TỔNG BỐN Ô = diện tích cả hình = tích phải tìm: 200 + 80 + 30 + 12 = 322. Đây chính là bản chất của phép đặt tính nhân hai chữ số (nhân từng phần rồi cộng, nhớ hàng).',
    obj:'tính 23 × 14 bằng 4 ô diện tích', mA10: 2, mA1: 3, mB10: 1, mB1: 4 },
  'quy-dong-mau-so': { model:'qds', ten:'Quy đồng mẫu số hai phân số',
    khoi_dong:'Cô có hai băng giấy bằng nhau. Băng thứ nhất chia 3 ô tô 2 ô (2/3). Băng thứ hai chia 4 ô tô 1 ô (1/4). Muốn đặt hai băng CẠNH NHAU để so hay cộng, ô của hai băng phải BẰNG NHAU. Làm sao đổi 2/3 và 1/4 thành hai phân số cùng một mẫu số mà giá trị KHÔNG đổi?',
    chot:'QUY ĐỒNG MẪU SỐ: đưa hai phân số về CÙNG một mẫu số mà giá trị mỗi phân số giữ nguyên, nhờ tính chất "nhân (hoặc chia) CẢ tử và mẫu với cùng một số khác 0 thì phân số không đổi". Muốn đổi a/b thành mẫu chung thì nhân tử và mẫu với THỪA SỐ còn lại. Cách chắc đúng cho lớp 4: lấy MẪU CHUNG = tích hai mẫu số (b × d), khi đó a/b = (a×d)/(b×d) và c/d = (c×b)/(d×b). Lỗi phổ biến: CHỈ đổi mẫu mà QUÊN nhân tử → phân số bị biến thành giá trị khác.',
    obj:'quy đồng 2/3 và 1/4 về cùng mẫu số', qdA: 2, qdB: 3, qdC: 1, qdD: 4 },
  'rut-ve-don-vi': { model:'rutdonvi', ten:'Bài toán rút về đơn vị (tìm giá trị một phần)',
    khoi_dong:'Mua 5 cái bút cùng loại hết 45 nghìn đồng. Hỏi mua 8 cái bút như thế thì hết bao nhiêu tiền? Vì sao muốn trả lời, ta phải biết giá CỦA MỘT cái bút trước?',
    chot:'RÚT VỀ ĐƠN VỊ: khi các phần HOÀN TOÀN NHƯ NHAU, ta tìm giá trị của MỘT phần rồi nhân lên. Bước 1 — chia: giá 1 món = tổng : số món = 45 : 5 = 9 nghìn. Bước 2 — nhân: 8 món = 9 × 8 = 72 nghìn. Sơ đồ đoạn thẳng: 5 ô bằng nhau chứa 45 nghìn, mỗi ô là 9 nghìn; rồi 8 ô như vậy cho 72 nghìn. Lỗi phổ biến: lấy 45 × 8 hoặc 45 : 8 (nhảy thẳng sang số phải tìm mà bỏ qua bước rút về 1 phần).',
    obj:'rút về đơn vị: 5 cái hết 45 nghìn, 8 cái hết bao nhiêu', rdN: 5, rdUnit: 9, rdM: 8 },
  'ucln-bcnn': { model:'bcnn', ten:'ƯCLN và BCNN của hai số (rút gọn tỉ số · mẫu chung nhỏ nhất)',
    khoi_dong:'Có hai dải băng dài 8 cm và 12 cm. Ta muốn lát kín cả hai dải bằng những Ô VUÔNG NHƯ NHAU, không cắt lẻ. Cạnh ô vuông to nhất là bao nhiêu? Và nếu xếp các BỘI của 8 (8,16,24,…) cùng các bội của 12 (12,24,36,…) thì hai hàng gặp nhau đầu tiên ở số nào?',
    chot:'ƯCLN là ước CHUNG LỚN NHẤT — ô vuông to nhất lát khít cả hai dải (ƯCLN(8,12)=4). BCNN là bội CHUNG NHỎ NHẤT — điểm hai hàng bội gặp nhau đầu tiên (BCNN(8,12)=24). ĐẲNG THỨC then chốt: a × b = BCNN(a,b) × ƯCLN(a,b), nên BCNN = a × b ÷ ƯCLN. Lỗi kinh điển: lấy BCNN = a × b (quên chia ƯCLN) — chỉ đúng khi hai số đôi một nguyên tố (ƯCLN=1). ƯCLN dùng để RÚT GỌN (psimp), BCNN dùng để QUY ĐỒNG mẫu chung nhỏ nhất (qds).',
    obj:'ƯCLN(8,12) và BCNN(8,12)', bcA: 8, bcB: 12 },
  'phan-phoi': { model:'phantphoi', ten:'Tính chất phân phối của phép nhân với phép cộng: a × (b + c) = a×b + a×c',
    khoi_dong:'Một giá bánh có 4 hàng, mỗi hàng xếp 5 cái bánh teal rồi ghép thêm 3 cái bánh vàng. Đếm tổng số bánh theo hai cách: (1) lấy 4 hàng nhân với (5 + 3) cột; (2) đếm riêng 4×5 bánh teal rồi cộng 4×3 bánh vàng. Hai cách cho cùng một kết quả không? Vì sao?',
    chot:'TÍNH CHẤT PHÂN PHỐI: nhân một số với một tổng = nhân số đó với TỪNG số hạng rồi cộng lại. 4 × (5 + 3) = 4×5 + 4×3 = 20 + 12 = 32. Kiểm tra lại: 4 × 8 = 32 — đúng bằng tổng hai phần. Trên sơ đồ ô vuông: hình chữ nhật cao 4, ngang 5+3=8 có 32 ô; kẻ một đường dọc chia thành mảng teal 4×5=20 ô và mảng vàng 4×3=12 ô; 20+12=32. Đây chính là bản chất phép đặt tính nhân nhiều chữ số (areamult) và mẹo tính nhanh. Lỗi kinh điển: chỉ nhân số ngoài với số hạng ĐẦU TIÊN rồi mới cộng số hạng sau — 4×(5+3) ≠ 4×5 + 3 = 23 (sai).',
    obj:'phân phối: 4 × (5 + 3)', pfA: 4, pfB: 5, pfC: 3 },
  'gap-giam-so-lan': { model:'gapso', ten:'Gấp một số lên nhiều lần · giảm một số đi nhiều lần (so sánh bội số)',
    khoi_dong:'Hàng trên xếp 3 cái kẹo. Hàng dưới xếp THÀNH 4 NHÓM, mỗi nhóm đúng 3 cái như hàng trên. Hàng dưới có bao nhiêu cái? Muốn được hàng dưới, ta đã "gấp" hàng trên lên mấy lần? Nếu ngược lại, cắt 12 cái kẹo thành 4 phần bằng nhau thì mỗi phần là mấy cái?',
    chot:'GẤP một số lên k lần = NHÂN số đó cho k (đoạn mới DÀI gấp k lần đoạn cũ). GIẢM một số đi k lần = CHIA số đó cho k (đoạn mới NGẮN đi k lần, số bị chia phải chia hết). Ví dụ 3 gấp 4 lần = 3 × 4 = 12; ngược lại 12 giảm 4 lần = 12 : 4 = 3 — hai phép là NGƯỢC nhau. Lỗi kinh điển: nhầm "gấp 4 lần của 3" thành 3 + 4 = 7 (CỘNG), hoặc nhầm "giảm" thành trừ (12 − 4). Từ "gấp k lần" ta có TỈ số B : A = k — nền của bài toán tỉ lệ thuận.',
    obj:'gấp 3 lên 4 lần; giảm 12 đi 4 lần', gpA: 3, gpK: 4 },
  'phan-so-voi-1': { model:'psvs1', ten:'Phân số so với 1: lớn hơn / bằng / bé hơn 1 (tử số ↔ mẫu số, liên hệ chia có dư)',
    khoi_dong:'Một cái bánh được chia đều thành 4 phần, cả cái bánh là 4/4 = 1. Bạn Minh lấy 7 phần như thế (7/4). 7 phần có nhiều hơn một cái bánh không? Cứ lấy đủ 4 phần là được một cái nguyên, vậy 7 phần được mấy cái nguyên và còn thừa mấy phần?',
    chot:'SO PHÂN SỐ VỚI 1 chỉ cần so TỬ số với MẪU số: tử > mẫu thì phân số lớn hơn 1; tử = mẫu thì bằng đúng 1; tử < mẫu thì bé hơn 1. Ví dụ 7/4: vì 7 > 4 nên 7/4 > 1. Lấy 7 : 4 = 1 dư 3, tức 7 = 1×4 + 3, nên 7/4 = 1 + 3/4 (một cái nguyên và ba phần tư). Đây chính là phép CHIA CÓ DƯ: thương = số đơn vị nguyên, số dư = tử của phần lẻ, mẫu giữ nguyên. Lỗi kinh điển: nghĩ "mẫu lớn thì phân số lớn" — 5/7 có mẫu 7 to nhưng 5 < 7 nên 5/7 BÉ hơn 1.',
    obj:'so 7/4 với 1', v1N: 7, v1D: 4 },
  'tb-cong-day-cach-deu': { model:'seqmean', ten:'Trung bình cộng của một dãy số cách đều (TBC = số chính giữa = (số đầu + số cuối) : 2)',
    khoi_dong:'Một dãy số được viết ra: 1, 3, 5, 7, 9. Em có nhận ra mỗi số hơn số đứng trước đúng 2 đơn vị (dãy CÁCH ĐỀU)? Muốn tìm trung bình cộng, thay vì cộng 1 + 3 + 5 + 7 + 9 rồi chia 5, em chỉ cần lấy (số đầu + số cuối) : 2 = (1 + 9) : 2 = 5. Vì sao kết quả lại ĐÚNG BẰNG số nằm chính giữa dãy?',
    chot:'Với DÃY SỐ CÁCH ĐỀU, TRUNG BÌNH CỘNG = (số hạng ĐẦU + số hạng CUỐI) : 2; nếu số số hạng LẺ thì nó đúng bằng SỐ CHÍNH GIỮA. Ví dụ 1, 3, 5, 7, 9: (1 + 9) : 2 = 5 = số giữa. Lý do (công thức Gauss): ghép đầu với cuối, thứ hai với áp chót, … mỗi cặp có tổng NHƯ NHAU (= số đầu + số cuối); nên Tổng = (số đầu + số cuối) × số số hạng : 2, chia lại cho số số hạng còn đúng (số đầu + số cuối) : 2. Lỗi kinh điển: lấy SỐ LỚN NHẤT làm trung bình, hoặc quên rằng quy tắc "số chính giữa" CHỈ ĐÚNG với dãy cách đều (dãy không đều phải cộng hết rồi chia). Nối với model mean (san bằng) và seq (dãy cách đều).',
    obj:'TBC của 1, 3, 5, 7, 9', smA: 1, smD: 2, smN: 5 },
  'bieu-do-cot-doi': { model:'dbar', ten:'Biểu đồ cột đôi: đọc và so sánh hai đại lượng theo từng nhóm (trai/gái của hai lớp)',
    khoi_dong:'Bảng sĩ số: Lớp 4A có 12 bạn trai và 8 bạn gái; Lớp 4B có 10 bạn trai và 12 bạn gái. Biểu đồ bên vẽ MỖI lớp bằng HAI cột đứng cạnh nhau (xanh = trai, vàng = gái). Nhìn chiều cao cột, lớp nào có nhiều bạn trai hơn? Mỗi lớp có tất cả bao nhiêu bạn?',
    chot:'BIỂU ĐỒ CỘT ĐÔI: ở mỗi nhóm (mỗi lớp) đặt HAI cột kề nhau để ĐỐI CHIẾU hai đại lượng cùng loại (trai và gái). Cách đọc: (1) đọc CHIỀU CAO từng cột theo đơn vị trên trục dọc; (2) CỘNG hai cột trong cùng nhóm ra TỔNG nhóm (4A = 12 + 8 = 20; 4B = 10 + 12 = 22); (3) SO SÁNH tổng giữa các nhóm (4B nhiều hơn 4A: 22 − 20 = 2 bạn). Lỗi kinh điển: chỉ nhìn CỘT CAO NHẤT của cả biểu đồ rồi kết luận, quên xét theo TỪNG CẶP trong nhóm. Đây là kỹ năng Thống kê lớp 4 (đọc bảng số liệu, biểu đồ), nối với biểu đồ cột đơn và bảng số liệu.',
    obj:'cột đôi sĩ số 4A/4B', dbT1: 12, dbG1: 8, dbT2: 10, dbG2: 12 },
};

const state = {
  lesson: 'phan-so-dau', step: 0,
  den: 4, shaded: [true, false, false, false],
  rows: 4, cols: 6,
  nlValue: 48, nlMax: 100, nlBase: 10,
  tens: 5, ones: 3,
  shBase: 6, shHeight: 4, shShear: 2, asRect: false,
  balL: 3, balR: 3,
  hour: 8, minute: 30,
  goc: 60,
  cL: 3, cW: 2, cH: 2,
  g100: 25,
  b0: 4, b1: 7, b2: 6, b3: 5, barSel: 1, dong: true,
  q0: 7, q1: 4, q2: 6, q3: 3, qSel: 0, san: true,
  tpA: 1, tpB: 2, tpTong: 30, tpShow: true,
  rhD1: 6, rhD2: 4, rhGhep: true,
  fbN1: 1, fbD1: 2, fbN2: 2, fbD2: 4,
  pR: 4, pB: 0, pY: 0, pAsk: 1,
  lnAng: 15, lnExt: false,
  dvSo: 17, dvNhom: 5,
  foD: 4, foN1: 1, foN2: 2, foOp: true,
  piU: 5, piH: false, piSel: 0, pi0: 3, pi1: 5, pi2: 2, pi3: 4,
  mtS: 120, mtV1: 40, mtV2: 20, mtT: 1,
  scCm: 3, scReal: 10,
  fcTotal: 12, fcDen: 3, fcTu: 1,
  rpBase: 2, rpNew: 6,
  unL: 3, unLu: 3, unR: 3, unRu: 0,
  aU: 0, a1: 5, a2: 0, a3: 0, bU: 0, b1: 4, b2: 8, b3: 0,
  pn: 15,
  tfDI: 0, tfN: 1,
  pStep: 0,
  aLen: 1, aHi: 9, bLen: 2, bHi: 1,
  dtRow: 0, dtCol: 0,
  boT: 3, boO: 2, bsT: 1, bsO: 5,
  mnC0: 3, mnC1: 2, mnC2: 1, mnC3: 1, mnSel: 0, mnPrice: 38000,
  dvT: 8, dvU: 4,
  pc0: 10, pc1: 5, pc2: 3, pc3: 2, pcSel: 0,
  lg0: 20, lg1: 24, lg2: 31, lg3: 29, lg4: 22, lgR: 2,
  svS: 120, svV: 40, svT: 3, svAsk: 0,
  coR: 5,
  trB: 10, trH: 6,
  tpA: 12, tpB: 6, tpH: 5,
  saA: 6, saB: 4, saC: 3,
  ordA: 2, ordB: 3, ordC: 4, ordK: 0,
  rcA: 6, rcB: 4,
  fdNum: 3, fdDen: 4, fdDiv: 2,
  dsWhich: 0, dsK: 1,
  fmN1: 1, fmD1: 2, fmN2: 1, fmD2: 3, fmOp: 1,
  daM: 3, daN: 4,
  dcAW: 3, dcAT: 4, dcBW: 2, dcBT: 5, dcOp: 1, dcSel: 0,
  ndA: 7, ndB: 2,
  luNum: 3, luUnit: 3,
  auNum: 1, auUnit: 3,
  vuNum: 1, vuUnit: 0,
  prK: 3, prX: 2,
  inK: 12, inX: 2,
  tuNum: 2, tuUnit: 0,
  mxTop: 5, mxDen: 3,
  dfExp: 1, dfNum: 7,
  zmMant: 3, zmZeros: 1, zmB: 4,
  agA: 27, agB: 43, agC: 15,
  drBig: 5, drSmall: 2, drDiff: 24,
  sdSum: 96, sdDiff: 12,
  sqA: 3, sqD: 4, sqN: 12,
  psN: 12, psD: 18,
  fcA: 3, fcB: 4, fcC: 5, fcD: 6,
  exA: 7, exB: 5,
  nhA: 24, nhM: 0,
  chSel: 0,
  exIdx: 0, exPick: null, exReveal: false,
  M: null, camOn: false, vote: { correct: 0, wrong: 0 }, boardWiped: false, handApplied: -1, twoApplied: '-1/-1',
};

const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));
const roundTo = (v, base) => Math.round(v / base) * base; // mốc tròn gần nhất
const ceilingFor = (M) => (M == null ? null : clamp(Math.round(M / 3), 12, 16)); // trần lượt = HÀM của sĩ số
const $ = (id) => document.getElementById(id);
const esc = (s) => String(s).replace(/[&<>"]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m]));
const cur = () => LESSONS[state.lesson];
const MDL = () => MODELS[cur().model];

